version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      PGDATA: 'var/lib/postgresql/data/pgdata'
    volumes:
      - db-data:/var/lib/postreqsl/data
    ports:
      - '6432:5432'
    container_name: postgres
    env_file:
      - ./server/.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d window-shop"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin'
    networks:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    restart: always
    ports:
      - "5050:7000"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    env_file:
      - ./server/.env

networks:
  postgres:
    driver: 'bridge'

volumes:
  db-data:
  pgadmin-data: